### ISSUE TITLE
rongcloud+BaiduMap will Crash.

### ISSUE THREAD

**Issue by dyguests** [rongcloud/demo-app-android-quick-start#2]
My project used BaiduMap.and when I import IMKit(rongcloud) module,The app is crash.
我的项目中使用了百度地图，在我加入IMKit(融云)后，app就崩溃了。
以下是Log:
crash log:

```
05-27 08:24:19.956 12605-12605/? E/art: No implementation found for long com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create() (tried Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create and Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create__)
05-27 08:24:19.957 12605-12605/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.fanhl.freetourdemo, PID: 12605
                                                   java.lang.UnsatisfiedLinkError: No implementation found for long com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create() (tried Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create and Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create__)
                                                       at com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create(Native Method)
                                                       at com.baidu.platform.comjni.map.commonmemcache.a.a(Unknown Source)
                                                       at com.baidu.platform.comapi.util.f.b(Unknown Source)
                                                       at com.baidu.platform.comapi.a.c(Unknown Source)
                                                       at com.baidu.platform.comapi.b.a(Unknown Source)
                                                       at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                       at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                       at com.fanhl.freetourdemo.App.onCreate(App.java:18)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4765)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

Is there anyway helpful?
请问有什么解决办法吗？

**Comment by Ityang** [comment]
看一下你加入的百度地图的 so 都有哪些架构的？我们提供了 4个架构的 so

**Comment by dyguests** [comment]
已解决，就是因为百度so架构不全的原因。非常感谢。
打扰了。。。
